# Generated by Django 4.1.5 on 2023-01-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.CharField(default='', max_length=256, verbose_name='stock description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='numberOf',
            field=models.IntegerField(default=1, verbose_name='number of stock, basket items excluded until purchased'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=64, verbose_name='stock item name'),
        ),
    ]
