# Generated by Django 4.1.5 on 2023-01-29 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_stock_description_stock_numberof_alter_stock_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=32, verbose_name='login user name')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockId', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.stock')),
                ('userId', models.ForeignKey(default='-1', on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.login')),
            ],
        ),
    ]
