# Generated by Django 4.1.5 on 2023-01-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_login_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='basketId',
            field=models.IntegerField(default=1, verbose_name='number of the basket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='userId',
            field=models.CharField(default='bern123444983', max_length=32, verbose_name='an internal identifier'),
            preserve_default=False,
        ),
    ]
