# Generated by Django 4.1.5 on 2023-01-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_basket_basketid_login_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='basketId',
            field=models.CharField(max_length=32, verbose_name='number of the basket'),
        ),
    ]
