# Generated by Django 4.1.5 on 2023-01-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_basket_basketid'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='numberOf',
            field=models.IntegerField(default=1, verbose_name='number of items in basket'),
            preserve_default=False,
        ),
    ]
