# Generated by Django 4.1.5 on 2023-01-30 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_basket_numberof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='userId',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.login', to_field='userId'),
        ),
        migrations.AlterField(
            model_name='login',
            name='userId',
            field=models.CharField(max_length=32, unique=True, verbose_name='an internal identifier'),
        ),
    ]
