# Generated by Django 4.1.5 on 2023-01-31 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_basket_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='userId',
            field=models.ForeignKey(blank=True, default='-1', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.login', to_field='userId'),
        ),
    ]
