# Generated by Django 4.1.5 on 2023-02-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_basket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stockId',
            field=models.CharField(default='changeme', max_length=32, verbose_name='external identifier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='userId',
            field=models.CharField(max_length=32, unique=True, verbose_name='external identifier'),
        ),
    ]
