# Generated by Django 4.1.5 on 2023-02-12 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_stock_stockid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='stockId',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.stock', to_field='stockId'),
        ),
    ]
